# Generated by Django 3.0.5 on 2020-04-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alboms_artists_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employees',
        ),
    ]
