# Generated by Django 3.0.5 on 2020-04-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_delete_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alboms',
            new_name='albums',
        ),
        migrations.RenameField(
            model_name='albums',
            old_name='AlbomId',
            new_name='AlbumId',
        ),
        migrations.RenameField(
            model_name='albums',
            old_name='albomName',
            new_name='albumName',
        ),
    ]
