# Generated by Django 3.0.5 on 2020-04-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200428_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='artistId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='AlbumId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='artistId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
