# Generated by Django 3.0.5 on 2020-05-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200428_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='imagePath',
            field=models.CharField(default='./assets/', max_length=100),
            preserve_default=False,
        ),
    ]
